export const ContentArea = () => (
  <div className="space-y-8 p-8">
    <h1 id="a" className="text-lg font-bold">Header 1</h1>
    <p >Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dapibus, purus sit amet imperdiet vestibulum, nulla arcu accumsan justo, at tempor neque nisl ac sapien. Proin et vestibulum urna. Vestibulum et mi sed lectus porttitor fermentum. Phasellus cursus volutpat arcu, a interdum tortor volutpat a. In sit amet mi sed tortor cursus rutrum. Duis auctor eget nisi a vulputate. Phasellus eros turpis, cursus vel interdum a, auctor vel turpis. Vivamus accumsan nunc laoreet arcu suscipit accumsan.

      Integer lacinia tincidunt consequat. Cras efficitur odio vitae congue facilisis. Integer eget lacus sit amet lectus laoreet rutrum. Nam laoreet lacinia quam. Aenean aliquam massa nec purus feugiat gravida. Nulla mauris metus, vestibulum vitae leo ac, egestas pharetra dolor. Suspendisse vitae augue nisl. Quisque tincidunt libero non dui mattis volutpat. Suspendisse ex dui, pretium sed vulputate sit amet, suscipit id nunc. Donec at iaculis mauris. Ut gravida odio vitae ipsum elementum, vitae egestas quam vestibulum. Cras vel fermentum odio. Integer molestie ullamcorper orci id efficitur. Nunc turpis purus, ornare non metus vitae, sodales rutrum ipsum. Vestibulum eget interdum nisi, et dictum augue.

      Morbi vel lacinia risus. Duis varius finibus ex, eget tempor mauris consectetur eget. Duis pretium tincidunt metus, non mollis justo pretium non. Maecenas euismod consectetur enim, in vehicula sapien convallis gravida. Nulla non suscipit mauris, ac dictum ipsum. Curabitur a quam vel justo elementum pretium. Phasellus eleifend cursus lacus sit amet mattis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer ac lacus lacus. Vestibulum at rutrum dui.

      Suspendisse id tortor a odio dictum consectetur interdum sed metus. Donec neque purus, vestibulum et ligula eget, mattis tempus nisl. Aenean diam ipsum, sodales ut sollicitudin in, laoreet sit amet nisi. Quisque nec magna laoreet risus mattis congue vitae nec neque. Mauris sed velit in justo eleifend volutpat. Phasellus in ligula erat. Morbi porta, urna ut eleifend luctus, nunc arcu ornare mauris, sed tincidunt lacus dolor eu lorem.

      Aliquam in dictum eros. Nullam porta aliquam risus vitae eleifend. Sed eget venenatis velit. Pellentesque suscipit congue ipsum in euismod. Vestibulum tincidunt neque sem, vitae egestas ipsum dictum sed. Nam tincidunt ipsum commodo odio eleifend, ut mollis odio accumsan. Vivamus laoreet ex elit, quis laoreet eros tristique sit amet. Donec eget erat lectus. Morbi consequat rhoncus metus eu pulvinar. Cras ligula nisl, euismod nec scelerisque non, commodo nec lorem. Mauris at scelerisque odio. Vivamus ac ligula ultrices, dictum erat sit amet, hendrerit ex. Aliquam lectus risus, facilisis in felis ac, viverra sollicitudin nisl. Proin non urna vel erat imperdiet semper ut eu velit. Phasellus vehicula imperdiet sem sit amet tempor.</p>
    <h1 id="b" className="text-lg font-bold">Header 2</h1>
    <p >Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut finibus ex nec lectus tempus, vitae efficitur diam tempus. Nunc pretium felis congue nunc pretium, at cursus arcu congue. Curabitur venenatis rutrum neque eget luctus. Integer sed porttitor purus, id euismod eros. Praesent maximus nunc odio, non mollis ex efficitur sit amet. Duis at velit lacinia nibh accumsan dignissim. Aliquam erat volutpat. Integer vitae nulla at nibh pellentesque facilisis fermentum quis ligula. Sed pellentesque metus quam, et ultricies ligula rhoncus in. Proin egestas augue quis imperdiet placerat. Curabitur dui nibh, finibus a mollis eu, hendrerit non dui. Sed et vulputate augue. Vestibulum commodo nisi at nibh viverra bibendum. Nullam felis nisi, venenatis at quam eu, bibendum dictum turpis. Fusce scelerisque risus turpis, sit amet aliquam nibh semper nec. Proin pellentesque finibus massa eu venenatis.

      Aenean porttitor ligula quis mauris feugiat hendrerit. Ut vitae libero scelerisque, pharetra turpis nec, sodales risus. Integer quis posuere lacus. In faucibus magna vel sem vulputate lacinia. Duis mattis sapien sed odio ullamcorper, sed posuere dui aliquam. Vestibulum rutrum sapien mi, at commodo magna scelerisque eget. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam ac porttitor sem, eu tristique sapien.

      Nam varius magna consequat quam scelerisque bibendum. Duis interdum, felis at dictum pellentesque, nunc ligula rutrum eros, convallis porta velit metus et augue. Donec non nunc lacus. Maecenas at dui at erat scelerisque pulvinar nec a mi. Proin gravida lorem dictum, efficitur libero eget, volutpat metus. Etiam vehicula tellus id mauris dignissim, nec hendrerit magna rhoncus. Vestibulum vel viverra elit. Cras et turpis ex. Nunc sed rhoncus ipsum, vel eleifend urna. Sed condimentum dignissim ante, eu mollis libero vehicula in. Donec congue tristique sodales. Fusce non rutrum dui, id varius nisl. Maecenas semper euismod turpis eget efficitur. Morbi luctus orci vel ante lobortis, et egestas tellus sagittis. Phasellus auctor laoreet dolor ut ultrices.

      Duis sed risus suscipit, porta lorem at, sagittis lorem. Suspendisse laoreet vehicula purus eget hendrerit. Donec convallis ultrices suscipit. Integer felis nibh, viverra nec quam auctor, aliquet imperdiet elit. Aenean non augue in felis accumsan tempor placerat eu erat. Aliquam consequat massa nunc, vel auctor arcu aliquet sit amet. Curabitur at urna a nunc dignissim ultrices sed ut ex. Morbi hendrerit, lacus non auctor dapibus, nisi quam molestie diam, vel iaculis risus dolor eget dui. Aenean facilisis tellus ex, nec ornare leo accumsan eu. Etiam posuere, tellus ut bibendum hendrerit, dui lacus sodales neque, at efficitur velit ligula quis quam.

      Phasellus a pretium velit. Aliquam convallis justo ac eleifend blandit. Sed porttitor dolor non lectus pretium, vel ullamcorper erat condimentum. Mauris orci est, semper vel imperdiet nec, lobortis at erat. Maecenas eget pretium lorem. Donec sapien felis, mattis in condimentum at, sodales quis elit. Sed turpis mauris, porttitor consectetur nisi in, venenatis efficitur lectus. Curabitur iaculis maximus lorem, nec laoreet eros blandit et. Curabitur semper ex luctus velit sollicitudin, et aliquam erat mattis. Phasellus finibus in lacus sed accumsan.</p>
    <h1 id="c" className="text-lg font-bold">Header 3</h1>
    <p >Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent malesuada turpis condimentum, tincidunt neque vitae, cursus massa. Suspendisse ac ante fermentum massa vestibulum feugiat. Aliquam iaculis iaculis pretium. Maecenas vestibulum ultricies risus, mattis suscipit justo maximus vitae. Pellentesque auctor posuere tortor, egestas viverra est porta id. Nam tristique lacus eget mi tincidunt, quis dignissim purus molestie. Sed id nisi nisl. Fusce faucibus metus eu nisl condimentum varius. Morbi facilisis nisl dapibus nulla tempus, at pulvinar turpis scelerisque. In aliquam arcu a ipsum varius convallis.

      Curabitur purus orci, sodales eget vulputate vel, interdum vel nunc. Suspendisse nec risus quis orci sollicitudin suscipit. Aliquam sit amet porttitor justo. Duis egestas lorem aliquam, commodo enim ac, accumsan lacus. Ut ullamcorper rhoncus lectus, efficitur fermentum velit. Etiam sollicitudin tellus eu est placerat, a tincidunt enim tincidunt. Fusce volutpat augue vel sapien aliquam, at sollicitudin elit efficitur. Etiam tincidunt varius purus quis porta. Nunc quis dui ut metus accumsan vulputate viverra quis arcu. Nullam lorem mauris, facilisis sed pulvinar sit amet, blandit non eros. Donec rhoncus tortor at commodo euismod. Curabitur laoreet dignissim augue id auctor.

      Ut gravida pellentesque dui, eu suscipit risus. Pellentesque iaculis nibh id nunc ultrices, vel porta neque hendrerit. Integer ac justo quam. Donec vitae neque eleifend, venenatis quam id, laoreet lacus. Phasellus justo nulla, interdum ac laoreet vel, gravida vel felis. Suspendisse eleifend finibus mi, eu accumsan lectus luctus non. Proin dictum, velit sed eleifend malesuada, risus ante maximus lorem, sed euismod odio nibh eget ipsum. Praesent accumsan sodales neque, quis porta neque imperdiet non. Fusce rhoncus odio nibh, in efficitur nunc volutpat vel.

      Fusce quis elementum nisi. Nulla facilisi. Donec ac neque sapien. Aliquam libero augue, semper in tincidunt ac, mollis gravida mi. Suspendisse id ipsum elit. Etiam risus ex, iaculis non viverra in, commodo eget erat. Pellentesque sem justo, ullamcorper id neque ac, mollis accumsan odio. In faucibus elementum tristique. Vestibulum id enim quis mi congue iaculis at eget orci. Aliquam eu interdum risus.

      Aenean id sapien eget nibh accumsan malesuada in id libero. Quisque aliquam eros a aliquam interdum. Proin in libero vitae neque tincidunt varius. Nam auctor metus nec mauris maximus, feugiat semper nibh vulputate. Aliquam ut scelerisque tellus. Suspendisse lacinia turpis sed massa tempor, ut vestibulum lacus facilisis. Sed vitae augue eu magna vulputate aliquet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam vitae efficitur sapien, et varius augue. Cras a aliquam dui, vel egestas sapien.</p>
  </div>
)
